hs_vsh_drawio_to_fb:
#  For the moment, push the stack installation to the ultimate containing build
#	stack install
	cp ~/.local/bin/hs_vsh_drawio_to_fb ~/bin

clean:
	rm -f ~/bin/hs_vsh_drawio_to_fb
